[program:php-fpm]
command=/usr/sbin/php-fpm8.3 -F
user=ubuntu
autostart=${ENABLE_PHP_FPM}
autorestart=true
stdout_logfile=/var/log/supervisor/php-fpm.log
stderr_logfile=/var/log/supervisor/php-fpm.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
user=ubuntu
autostart=${ENABLE_NGINX}
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.log

[program:cron]
command=/usr/local/bin/supercronic /etc/crontabs/merged
user=ubuntu
autostart=${ENABLE_CRON}
autorestart=true
stdout_logfile=/var/log/supervisor/cron.log
stderr_logfile=/var/log/supervisor/cron.log

[program:sshd]
command=/usr/sbin/sshd -D -e
user=ubuntu
autostart=${ENABLE_SSHD}
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd.log
