FROM opensearchproject/opensearch:2.19.5

RUN /usr/share/opensearch/bin/opensearch-plugin install --batch analysis-phonetic
RUN /usr/share/opensearch/bin/opensearch-plugin install --batch analysis-icu
