http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/supervisor/nginx-access.log main;
    error_log /var/log/supervisor/nginx-error.log;

    sendfile ${NGINX_SENDFILE};
    tcp_nopush ${NGINX_TCP_NOPUSH};
    tcp_nodelay ${NGINX_TCP_NODELAY};
    keepalive_timeout ${NGINX_KEEPALIVE_TIMEOUT};
    types_hash_max_size 2048;
    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};

    client_body_temp_path /tmp/nginx_client_body;
    proxy_temp_path /tmp/nginx_proxy;
    fastcgi_temp_path /tmp/nginx_fastcgi;
    uwsgi_temp_path /tmp/nginx_uwsgi;
    scgi_temp_path /tmp/nginx_scgi;

    # Trust Traefik forwarded headers
    set_real_ip_from 0.0.0.0/0;
    real_ip_header X-Forwarded-For;

    map $http_x_forwarded_proto $fastcgi_https {
        default off;
        https on;
    }

    include /etc/nginx/conf.d/http/*.conf;
    include /etc/nginx/server.conf;
}
